/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.insurtech.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import dev.insurtech.api.DateTimeHelper;
import java.time.LocalDateTime;

/**
 * This is a model class for Attributes type.
 */
public class Attributes {
    private LocalDateTime createdDate;
    private LocalDateTime modifiedDate;
    private Object factors;

    /**
     * Default constructor.
     */
    public Attributes() {
    }

    /**
     * Initialization constructor.
     * @param  factors  Object value for factors.
     * @param  createdDate  LocalDateTime value for createdDate.
     * @param  modifiedDate  LocalDateTime value for modifiedDate.
     */
    public Attributes(
            Object factors,
            LocalDateTime createdDate,
            LocalDateTime modifiedDate) {
        this.createdDate = createdDate;
        this.modifiedDate = modifiedDate;
        this.factors = factors;
    }

    /**
     * Getter for CreatedDate.
     * Date time when this resource was created in our system.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("created_date")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getCreatedDate() {
        return createdDate;
    }

    /**
     * Setter for CreatedDate.
     * Date time when this resource was created in our system.
     * @param createdDate Value for LocalDateTime
     */
    @JsonSetter("created_date")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setCreatedDate(LocalDateTime createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * Getter for ModifiedDate.
     * Date time when this resource was last modified in our system.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("modified_date")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getModifiedDate() {
        return modifiedDate;
    }

    /**
     * Setter for ModifiedDate.
     * Date time when this resource was last modified in our system.
     * @param modifiedDate Value for LocalDateTime
     */
    @JsonSetter("modified_date")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setModifiedDate(LocalDateTime modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    /**
     * Getter for Factors.
     * Specific ratable factors that apply to this Insured Risk. The content must fully adhere to a
     * product-specific, pre-defined schema.
     * @return Returns the Object
     */
    @JsonGetter("factors")
    public Object getFactors() {
        return factors;
    }

    /**
     * Setter for Factors.
     * Specific ratable factors that apply to this Insured Risk. The content must fully adhere to a
     * product-specific, pre-defined schema.
     * @param factors Value for Object
     */
    @JsonSetter("factors")
    public void setFactors(Object factors) {
        this.factors = factors;
    }

    /**
     * Converts this Attributes into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Attributes [" + "factors=" + factors + ", createdDate=" + createdDate
                + ", modifiedDate=" + modifiedDate + "]";
    }

    /**
     * Builds a new {@link Attributes.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Attributes.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(factors)
                .createdDate(getCreatedDate())
                .modifiedDate(getModifiedDate());
        return builder;
    }

    /**
     * Class to build instances of {@link Attributes}.
     */
    public static class Builder {
        private Object factors;
        private LocalDateTime createdDate;
        private LocalDateTime modifiedDate;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  factors  Object value for factors.
         */
        public Builder(Object factors) {
            this.factors = factors;
        }

        /**
         * Setter for factors.
         * @param  factors  Object value for factors.
         * @return Builder
         */
        public Builder factors(Object factors) {
            this.factors = factors;
            return this;
        }

        /**
         * Setter for createdDate.
         * @param  createdDate  LocalDateTime value for createdDate.
         * @return Builder
         */
        public Builder createdDate(LocalDateTime createdDate) {
            this.createdDate = createdDate;
            return this;
        }

        /**
         * Setter for modifiedDate.
         * @param  modifiedDate  LocalDateTime value for modifiedDate.
         * @return Builder
         */
        public Builder modifiedDate(LocalDateTime modifiedDate) {
            this.modifiedDate = modifiedDate;
            return this;
        }

        /**
         * Builds a new {@link Attributes} object using the set fields.
         * @return {@link Attributes}
         */
        public Attributes build() {
            return new Attributes(factors, createdDate, modifiedDate);
        }
    }
}
