/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.insurtech.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Attributes2 type.
 */
public class Attributes2 {
    private String quoteNumber;
    private String installmentPlan;
    private String stripeToken;
    private String externalId;

    /**
     * Default constructor.
     */
    public Attributes2() {
    }

    /**
     * Initialization constructor.
     * @param  quoteNumber  String value for quoteNumber.
     * @param  installmentPlan  String value for installmentPlan.
     * @param  stripeToken  String value for stripeToken.
     * @param  externalId  String value for externalId.
     */
    public Attributes2(
            String quoteNumber,
            String installmentPlan,
            String stripeToken,
            String externalId) {
        this.quoteNumber = quoteNumber;
        this.installmentPlan = installmentPlan;
        this.stripeToken = stripeToken;
        this.externalId = externalId;
    }

    /**
     * Getter for QuoteNumber.
     * Quote number received from quote creation.
     * @return Returns the String
     */
    @JsonGetter("quote_number")
    public String getQuoteNumber() {
        return quoteNumber;
    }

    /**
     * Setter for QuoteNumber.
     * Quote number received from quote creation.
     * @param quoteNumber Value for String
     */
    @JsonSetter("quote_number")
    public void setQuoteNumber(String quoteNumber) {
        this.quoteNumber = quoteNumber;
    }

    /**
     * Getter for InstallmentPlan.
     * Value from the set which controls invoicing and billing. This is dependent on your product's
     * configuration.
     * @return Returns the String
     */
    @JsonGetter("installment_plan")
    public String getInstallmentPlan() {
        return installmentPlan;
    }

    /**
     * Setter for InstallmentPlan.
     * Value from the set which controls invoicing and billing. This is dependent on your product's
     * configuration.
     * @param installmentPlan Value for String
     */
    @JsonSetter("installment_plan")
    public void setInstallmentPlan(String installmentPlan) {
        this.installmentPlan = installmentPlan;
    }

    /**
     * Getter for StripeToken.
     * Stripe credit card token that will be used for charge authorization.
     * @return Returns the String
     */
    @JsonGetter("stripe_token")
    public String getStripeToken() {
        return stripeToken;
    }

    /**
     * Setter for StripeToken.
     * Stripe credit card token that will be used for charge authorization.
     * @param stripeToken Value for String
     */
    @JsonSetter("stripe_token")
    public void setStripeToken(String stripeToken) {
        this.stripeToken = stripeToken;
    }

    /**
     * Getter for ExternalId.
     * Any value you wish to associate with this resource such as an ID from your system.
     * @return Returns the String
     */
    @JsonGetter("external_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getExternalId() {
        return externalId;
    }

    /**
     * Setter for ExternalId.
     * Any value you wish to associate with this resource such as an ID from your system.
     * @param externalId Value for String
     */
    @JsonSetter("external_id")
    public void setExternalId(String externalId) {
        this.externalId = externalId;
    }

    /**
     * Converts this Attributes2 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Attributes2 [" + "quoteNumber=" + quoteNumber + ", installmentPlan="
                + installmentPlan + ", stripeToken=" + stripeToken + ", externalId=" + externalId
                + "]";
    }

    /**
     * Builds a new {@link Attributes2.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Attributes2.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(quoteNumber, installmentPlan, stripeToken)
                .externalId(getExternalId());
        return builder;
    }

    /**
     * Class to build instances of {@link Attributes2}.
     */
    public static class Builder {
        private String quoteNumber;
        private String installmentPlan;
        private String stripeToken;
        private String externalId;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  quoteNumber  String value for quoteNumber.
         * @param  installmentPlan  String value for installmentPlan.
         * @param  stripeToken  String value for stripeToken.
         */
        public Builder(String quoteNumber, String installmentPlan, String stripeToken) {
            this.quoteNumber = quoteNumber;
            this.installmentPlan = installmentPlan;
            this.stripeToken = stripeToken;
        }

        /**
         * Setter for quoteNumber.
         * @param  quoteNumber  String value for quoteNumber.
         * @return Builder
         */
        public Builder quoteNumber(String quoteNumber) {
            this.quoteNumber = quoteNumber;
            return this;
        }

        /**
         * Setter for installmentPlan.
         * @param  installmentPlan  String value for installmentPlan.
         * @return Builder
         */
        public Builder installmentPlan(String installmentPlan) {
            this.installmentPlan = installmentPlan;
            return this;
        }

        /**
         * Setter for stripeToken.
         * @param  stripeToken  String value for stripeToken.
         * @return Builder
         */
        public Builder stripeToken(String stripeToken) {
            this.stripeToken = stripeToken;
            return this;
        }

        /**
         * Setter for externalId.
         * @param  externalId  String value for externalId.
         * @return Builder
         */
        public Builder externalId(String externalId) {
            this.externalId = externalId;
            return this;
        }

        /**
         * Builds a new {@link Attributes2} object using the set fields.
         * @return {@link Attributes2}
         */
        public Attributes2 build() {
            return new Attributes2(quoteNumber, installmentPlan, stripeToken, externalId);
        }
    }
}
