/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.insurtech.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Coverage type.
 */
public class Coverage {
    private Data21 data;

    /**
     * Default constructor.
     */
    public Coverage() {
    }

    /**
     * Initialization constructor.
     * @param  data  Data21 value for data.
     */
    public Coverage(
            Data21 data) {
        this.data = data;
    }

    /**
     * Getter for Data.
     * Provided data for this product coverage relationship.
     * @return Returns the Data21
     */
    @JsonGetter("data")
    public Data21 getData() {
        return data;
    }

    /**
     * Setter for Data.
     * Provided data for this product coverage relationship.
     * @param data Value for Data21
     */
    @JsonSetter("data")
    public void setData(Data21 data) {
        this.data = data;
    }

    /**
     * Converts this Coverage into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Coverage [" + "data=" + data + "]";
    }

    /**
     * Builds a new {@link Coverage.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Coverage.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(data);
        return builder;
    }

    /**
     * Class to build instances of {@link Coverage}.
     */
    public static class Builder {
        private Data21 data;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  data  Data21 value for data.
         */
        public Builder(Data21 data) {
            this.data = data;
        }

        /**
         * Setter for data.
         * @param  data  Data21 value for data.
         * @return Builder
         */
        public Builder data(Data21 data) {
            this.data = data;
            return this;
        }

        /**
         * Builds a new {@link Coverage} object using the set fields.
         * @return {@link Coverage}
         */
        public Coverage build() {
            return new Coverage(data);
        }
    }
}
