/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.insurtech.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for Coverages2 type.
 */
public class Coverages2 {
    private List<Data40> data;

    /**
     * Default constructor.
     */
    public Coverages2() {
    }

    /**
     * Initialization constructor.
     * @param  data  List of Data40 value for data.
     */
    public Coverages2(
            List<Data40> data) {
        this.data = data;
    }

    /**
     * Getter for Data.
     * List of objects with coverage local IDs.
     * @return Returns the List of Data40
     */
    @JsonGetter("data")
    public List<Data40> getData() {
        return data;
    }

    /**
     * Setter for Data.
     * List of objects with coverage local IDs.
     * @param data Value for List of Data40
     */
    @JsonSetter("data")
    public void setData(List<Data40> data) {
        this.data = data;
    }

    /**
     * Converts this Coverages2 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Coverages2 [" + "data=" + data + "]";
    }

    /**
     * Builds a new {@link Coverages2.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Coverages2.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(data);
        return builder;
    }

    /**
     * Class to build instances of {@link Coverages2}.
     */
    public static class Builder {
        private List<Data40> data;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  data  List of Data40 value for data.
         */
        public Builder(List<Data40> data) {
            this.data = data;
        }

        /**
         * Setter for data.
         * @param  data  List of Data40 value for data.
         * @return Builder
         */
        public Builder data(List<Data40> data) {
            this.data = data;
            return this;
        }

        /**
         * Builds a new {@link Coverages2} object using the set fields.
         * @return {@link Coverages2}
         */
        public Coverages2 build() {
            return new Coverages2(data);
        }
    }
}
