/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.insurtech.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Data45 type.
 */
public class Data45 {
    private String type;
    private String id;
    private Attributes9 attributes;
    private Relationships11 relationships;

    /**
     * Default constructor.
     */
    public Data45() {
        type = "quote";
    }

    /**
     * Initialization constructor.
     * @param  type  String value for type.
     * @param  id  String value for id.
     * @param  attributes  Attributes9 value for attributes.
     * @param  relationships  Relationships11 value for relationships.
     */
    public Data45(
            String type,
            String id,
            Attributes9 attributes,
            Relationships11 relationships) {
        this.type = type;
        this.id = id;
        this.attributes = attributes;
        this.relationships = relationships;
    }

    /**
     * Getter for Type.
     * The type of resource being represented.
     * @return Returns the String
     */
    @JsonGetter("type")
    public String getType() {
        return type;
    }

    /**
     * Setter for Type.
     * The type of resource being represented.
     * @param type Value for String
     */
    @JsonSetter("type")
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Getter for Id.
     * Unique Boost generated identifier for this resource that adheres to the above pattern.
     * @return Returns the String
     */
    @JsonGetter("id")
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * Unique Boost generated identifier for this resource that adheres to the above pattern.
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for Attributes.
     * Attributes for this object.
     * @return Returns the Attributes9
     */
    @JsonGetter("attributes")
    public Attributes9 getAttributes() {
        return attributes;
    }

    /**
     * Setter for Attributes.
     * Attributes for this object.
     * @param attributes Value for Attributes9
     */
    @JsonSetter("attributes")
    public void setAttributes(Attributes9 attributes) {
        this.attributes = attributes;
    }

    /**
     * Getter for Relationships.
     * Related items.
     * @return Returns the Relationships11
     */
    @JsonGetter("relationships")
    public Relationships11 getRelationships() {
        return relationships;
    }

    /**
     * Setter for Relationships.
     * Related items.
     * @param relationships Value for Relationships11
     */
    @JsonSetter("relationships")
    public void setRelationships(Relationships11 relationships) {
        this.relationships = relationships;
    }

    /**
     * Converts this Data45 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Data45 [" + "type=" + type + ", id=" + id + ", attributes=" + attributes
                + ", relationships=" + relationships + "]";
    }

    /**
     * Builds a new {@link Data45.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Data45.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(type, id, attributes, relationships);
        return builder;
    }

    /**
     * Class to build instances of {@link Data45}.
     */
    public static class Builder {
        private String type = "quote";
        private String id;
        private Attributes9 attributes;
        private Relationships11 relationships;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  type  String value for type.
         * @param  id  String value for id.
         * @param  attributes  Attributes9 value for attributes.
         * @param  relationships  Relationships11 value for relationships.
         */
        public Builder(String type, String id, Attributes9 attributes,
                Relationships11 relationships) {
            this.type = type;
            this.id = id;
            this.attributes = attributes;
            this.relationships = relationships;
        }

        /**
         * Setter for type.
         * @param  type  String value for type.
         * @return Builder
         */
        public Builder type(String type) {
            this.type = type;
            return this;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for attributes.
         * @param  attributes  Attributes9 value for attributes.
         * @return Builder
         */
        public Builder attributes(Attributes9 attributes) {
            this.attributes = attributes;
            return this;
        }

        /**
         * Setter for relationships.
         * @param  relationships  Relationships11 value for relationships.
         * @return Builder
         */
        public Builder relationships(Relationships11 relationships) {
            this.relationships = relationships;
            return this;
        }

        /**
         * Builds a new {@link Data45} object using the set fields.
         * @return {@link Data45}
         */
        public Data45 build() {
            return new Data45(type, id, attributes, relationships);
        }
    }
}
