/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.insurtech.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.UUID;

/**
 * This is a model class for Data type.
 */
public class Data {
    private String type;
    private UUID id;
    private Attributes attributes;
    private Relationships relationships;

    /**
     * Default constructor.
     */
    public Data() {
        type = "insured_risk";
    }

    /**
     * Initialization constructor.
     * @param  type  String value for type.
     * @param  attributes  Attributes value for attributes.
     * @param  relationships  Relationships value for relationships.
     * @param  id  UUID value for id.
     */
    public Data(
            String type,
            Attributes attributes,
            Relationships relationships,
            UUID id) {
        this.type = type;
        this.id = id;
        this.attributes = attributes;
        this.relationships = relationships;
    }

    /**
     * Getter for Type.
     * The type of resource being represented.
     * @return Returns the String
     */
    @JsonGetter("type")
    public String getType() {
        return type;
    }

    /**
     * Setter for Type.
     * The type of resource being represented.
     * @param type Value for String
     */
    @JsonSetter("type")
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Getter for Id.
     * @return Returns the UUID
     */
    @JsonGetter("id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public UUID getId() {
        return id;
    }

    /**
     * Setter for Id.
     * @param id Value for UUID
     */
    @JsonSetter("id")
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for Attributes.
     * Attributes that describe an Insured Risk.
     * @return Returns the Attributes
     */
    @JsonGetter("attributes")
    public Attributes getAttributes() {
        return attributes;
    }

    /**
     * Setter for Attributes.
     * Attributes that describe an Insured Risk.
     * @param attributes Value for Attributes
     */
    @JsonSetter("attributes")
    public void setAttributes(Attributes attributes) {
        this.attributes = attributes;
    }

    /**
     * Getter for Relationships.
     * Related objects.
     * @return Returns the Relationships
     */
    @JsonGetter("relationships")
    public Relationships getRelationships() {
        return relationships;
    }

    /**
     * Setter for Relationships.
     * Related objects.
     * @param relationships Value for Relationships
     */
    @JsonSetter("relationships")
    public void setRelationships(Relationships relationships) {
        this.relationships = relationships;
    }

    /**
     * Converts this Data into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Data [" + "type=" + type + ", attributes=" + attributes + ", relationships="
                + relationships + ", id=" + id + "]";
    }

    /**
     * Builds a new {@link Data.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Data.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(type, attributes, relationships)
                .id(getId());
        return builder;
    }

    /**
     * Class to build instances of {@link Data}.
     */
    public static class Builder {
        private String type = "insured_risk";
        private Attributes attributes;
        private Relationships relationships;
        private UUID id;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  type  String value for type.
         * @param  attributes  Attributes value for attributes.
         * @param  relationships  Relationships value for relationships.
         */
        public Builder(String type, Attributes attributes, Relationships relationships) {
            this.type = type;
            this.attributes = attributes;
            this.relationships = relationships;
        }

        /**
         * Setter for type.
         * @param  type  String value for type.
         * @return Builder
         */
        public Builder type(String type) {
            this.type = type;
            return this;
        }

        /**
         * Setter for attributes.
         * @param  attributes  Attributes value for attributes.
         * @return Builder
         */
        public Builder attributes(Attributes attributes) {
            this.attributes = attributes;
            return this;
        }

        /**
         * Setter for relationships.
         * @param  relationships  Relationships value for relationships.
         * @return Builder
         */
        public Builder relationships(Relationships relationships) {
            this.relationships = relationships;
            return this;
        }

        /**
         * Setter for id.
         * @param  id  UUID value for id.
         * @return Builder
         */
        public Builder id(UUID id) {
            this.id = id;
            return this;
        }

        /**
         * Builds a new {@link Data} object using the set fields.
         * @return {@link Data}
         */
        public Data build() {
            return new Data(type, attributes, relationships, id);
        }
    }
}
