/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.insurtech.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.UUID;

/**
 * This is a model class for Data9 type.
 */
public class Data9 {
    private String type;
    private UUID id;
    private Attributes3 attributes;
    private Relationships3 relationships;

    /**
     * Default constructor.
     */
    public Data9() {
        type = "policy";
    }

    /**
     * Initialization constructor.
     * @param  type  String value for type.
     * @param  id  UUID value for id.
     * @param  attributes  Attributes3 value for attributes.
     * @param  relationships  Relationships3 value for relationships.
     */
    public Data9(
            String type,
            UUID id,
            Attributes3 attributes,
            Relationships3 relationships) {
        this.type = type;
        this.id = id;
        this.attributes = attributes;
        this.relationships = relationships;
    }

    /**
     * Getter for Type.
     * The type of resource being represented.
     * @return Returns the String
     */
    @JsonGetter("type")
    public String getType() {
        return type;
    }

    /**
     * Setter for Type.
     * The type of resource being represented.
     * @param type Value for String
     */
    @JsonSetter("type")
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Getter for Id.
     * @return Returns the UUID
     */
    @JsonGetter("id")
    public UUID getId() {
        return id;
    }

    /**
     * Setter for Id.
     * @param id Value for UUID
     */
    @JsonSetter("id")
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for Attributes.
     * Attributes that describe a policy resource with optional writeable money fields.
     * @return Returns the Attributes3
     */
    @JsonGetter("attributes")
    public Attributes3 getAttributes() {
        return attributes;
    }

    /**
     * Setter for Attributes.
     * Attributes that describe a policy resource with optional writeable money fields.
     * @param attributes Value for Attributes3
     */
    @JsonSetter("attributes")
    public void setAttributes(Attributes3 attributes) {
        this.attributes = attributes;
    }

    /**
     * Getter for Relationships.
     * Items related to this policy.
     * @return Returns the Relationships3
     */
    @JsonGetter("relationships")
    public Relationships3 getRelationships() {
        return relationships;
    }

    /**
     * Setter for Relationships.
     * Items related to this policy.
     * @param relationships Value for Relationships3
     */
    @JsonSetter("relationships")
    public void setRelationships(Relationships3 relationships) {
        this.relationships = relationships;
    }

    /**
     * Converts this Data9 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Data9 [" + "type=" + type + ", id=" + id + ", attributes=" + attributes
                + ", relationships=" + relationships + "]";
    }

    /**
     * Builds a new {@link Data9.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Data9.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(type, id, attributes, relationships);
        return builder;
    }

    /**
     * Class to build instances of {@link Data9}.
     */
    public static class Builder {
        private String type = "policy";
        private UUID id;
        private Attributes3 attributes;
        private Relationships3 relationships;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  type  String value for type.
         * @param  id  UUID value for id.
         * @param  attributes  Attributes3 value for attributes.
         * @param  relationships  Relationships3 value for relationships.
         */
        public Builder(String type, UUID id, Attributes3 attributes, Relationships3 relationships) {
            this.type = type;
            this.id = id;
            this.attributes = attributes;
            this.relationships = relationships;
        }

        /**
         * Setter for type.
         * @param  type  String value for type.
         * @return Builder
         */
        public Builder type(String type) {
            this.type = type;
            return this;
        }

        /**
         * Setter for id.
         * @param  id  UUID value for id.
         * @return Builder
         */
        public Builder id(UUID id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for attributes.
         * @param  attributes  Attributes3 value for attributes.
         * @return Builder
         */
        public Builder attributes(Attributes3 attributes) {
            this.attributes = attributes;
            return this;
        }

        /**
         * Setter for relationships.
         * @param  relationships  Relationships3 value for relationships.
         * @return Builder
         */
        public Builder relationships(Relationships3 relationships) {
            this.relationships = relationships;
            return this;
        }

        /**
         * Builds a new {@link Data9} object using the set fields.
         * @return {@link Data9}
         */
        public Data9 build() {
            return new Data9(type, id, attributes, relationships);
        }
    }
}
