/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.insurtech.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Data6 type.
 */
public class Data6 {
    private String type;
    private Attributes2 attributes;
    private Relationships2 relationships;

    /**
     * Default constructor.
     */
    public Data6() {
        type = "policy";
    }

    /**
     * Initialization constructor.
     * @param  type  String value for type.
     * @param  attributes  Attributes2 value for attributes.
     * @param  relationships  Relationships2 value for relationships.
     */
    public Data6(
            String type,
            Attributes2 attributes,
            Relationships2 relationships) {
        this.type = type;
        this.attributes = attributes;
        this.relationships = relationships;
    }

    /**
     * Getter for Type.
     * The type of resource being represented.
     * @return Returns the String
     */
    @JsonGetter("type")
    public String getType() {
        return type;
    }

    /**
     * Setter for Type.
     * The type of resource being represented.
     * @param type Value for String
     */
    @JsonSetter("type")
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Getter for Attributes.
     * Attributes for this policy.
     * @return Returns the Attributes2
     */
    @JsonGetter("attributes")
    public Attributes2 getAttributes() {
        return attributes;
    }

    /**
     * Setter for Attributes.
     * Attributes for this policy.
     * @param attributes Value for Attributes2
     */
    @JsonSetter("attributes")
    public void setAttributes(Attributes2 attributes) {
        this.attributes = attributes;
    }

    /**
     * Getter for Relationships.
     * Related items.
     * @return Returns the Relationships2
     */
    @JsonGetter("relationships")
    public Relationships2 getRelationships() {
        return relationships;
    }

    /**
     * Setter for Relationships.
     * Related items.
     * @param relationships Value for Relationships2
     */
    @JsonSetter("relationships")
    public void setRelationships(Relationships2 relationships) {
        this.relationships = relationships;
    }

    /**
     * Converts this Data6 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Data6 [" + "type=" + type + ", attributes=" + attributes + ", relationships="
                + relationships + "]";
    }

    /**
     * Builds a new {@link Data6.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Data6.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(type, attributes, relationships);
        return builder;
    }

    /**
     * Class to build instances of {@link Data6}.
     */
    public static class Builder {
        private String type = "policy";
        private Attributes2 attributes;
        private Relationships2 relationships;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  type  String value for type.
         * @param  attributes  Attributes2 value for attributes.
         * @param  relationships  Relationships2 value for relationships.
         */
        public Builder(String type, Attributes2 attributes, Relationships2 relationships) {
            this.type = type;
            this.attributes = attributes;
            this.relationships = relationships;
        }

        /**
         * Setter for type.
         * @param  type  String value for type.
         * @return Builder
         */
        public Builder type(String type) {
            this.type = type;
            return this;
        }

        /**
         * Setter for attributes.
         * @param  attributes  Attributes2 value for attributes.
         * @return Builder
         */
        public Builder attributes(Attributes2 attributes) {
            this.attributes = attributes;
            return this;
        }

        /**
         * Setter for relationships.
         * @param  relationships  Relationships2 value for relationships.
         * @return Builder
         */
        public Builder relationships(Relationships2 relationships) {
            this.relationships = relationships;
            return this;
        }

        /**
         * Builds a new {@link Data6} object using the set fields.
         * @return {@link Data6}
         */
        public Data6 build() {
            return new Data6(type, attributes, relationships);
        }
    }
}
