/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.insurtech.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
import java.util.UUID;

/**
 * This is a model class for Data24 type.
 */
public class Data24 {
    private String type;
    private UUID id;
    private Attributes6 attributes;
    private Relationships3 relationships;
    private List<Object> included;

    /**
     * Default constructor.
     */
    public Data24() {
        type = "policy";
    }

    /**
     * Initialization constructor.
     * @param  type  String value for type.
     * @param  id  UUID value for id.
     * @param  attributes  Attributes6 value for attributes.
     * @param  relationships  Relationships3 value for relationships.
     * @param  included  List of Object value for included.
     */
    public Data24(
            String type,
            UUID id,
            Attributes6 attributes,
            Relationships3 relationships,
            List<Object> included) {
        this.type = type;
        this.id = id;
        this.attributes = attributes;
        this.relationships = relationships;
        this.included = included;
    }

    /**
     * Getter for Type.
     * The type of resource being represented.
     * @return Returns the String
     */
    @JsonGetter("type")
    public String getType() {
        return type;
    }

    /**
     * Setter for Type.
     * The type of resource being represented.
     * @param type Value for String
     */
    @JsonSetter("type")
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Getter for Id.
     * @return Returns the UUID
     */
    @JsonGetter("id")
    public UUID getId() {
        return id;
    }

    /**
     * Setter for Id.
     * @param id Value for UUID
     */
    @JsonSetter("id")
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for Attributes.
     * Attributes that describe a policy resource with optional writeable money fields.
     * @return Returns the Attributes6
     */
    @JsonGetter("attributes")
    public Attributes6 getAttributes() {
        return attributes;
    }

    /**
     * Setter for Attributes.
     * Attributes that describe a policy resource with optional writeable money fields.
     * @param attributes Value for Attributes6
     */
    @JsonSetter("attributes")
    public void setAttributes(Attributes6 attributes) {
        this.attributes = attributes;
    }

    /**
     * Getter for Relationships.
     * Items related to this policy.
     * @return Returns the Relationships3
     */
    @JsonGetter("relationships")
    public Relationships3 getRelationships() {
        return relationships;
    }

    /**
     * Setter for Relationships.
     * Items related to this policy.
     * @param relationships Value for Relationships3
     */
    @JsonSetter("relationships")
    public void setRelationships(Relationships3 relationships) {
        this.relationships = relationships;
    }

    /**
     * Getter for Included.
     * Array of included objects which provide additional data about an object from the above
     * `data.relationships`.
     * @return Returns the List of Object
     */
    @JsonGetter("included")
    public List<Object> getIncluded() {
        return included;
    }

    /**
     * Setter for Included.
     * Array of included objects which provide additional data about an object from the above
     * `data.relationships`.
     * @param included Value for List of Object
     */
    @JsonSetter("included")
    public void setIncluded(List<Object> included) {
        this.included = included;
    }

    /**
     * Converts this Data24 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Data24 [" + "type=" + type + ", id=" + id + ", attributes=" + attributes
                + ", relationships=" + relationships + ", included=" + included + "]";
    }

    /**
     * Builds a new {@link Data24.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Data24.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(type, id, attributes, relationships, included);
        return builder;
    }

    /**
     * Class to build instances of {@link Data24}.
     */
    public static class Builder {
        private String type = "policy";
        private UUID id;
        private Attributes6 attributes;
        private Relationships3 relationships;
        private List<Object> included;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  type  String value for type.
         * @param  id  UUID value for id.
         * @param  attributes  Attributes6 value for attributes.
         * @param  relationships  Relationships3 value for relationships.
         * @param  included  List of Object value for included.
         */
        public Builder(String type, UUID id, Attributes6 attributes, Relationships3 relationships,
                List<Object> included) {
            this.type = type;
            this.id = id;
            this.attributes = attributes;
            this.relationships = relationships;
            this.included = included;
        }

        /**
         * Setter for type.
         * @param  type  String value for type.
         * @return Builder
         */
        public Builder type(String type) {
            this.type = type;
            return this;
        }

        /**
         * Setter for id.
         * @param  id  UUID value for id.
         * @return Builder
         */
        public Builder id(UUID id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for attributes.
         * @param  attributes  Attributes6 value for attributes.
         * @return Builder
         */
        public Builder attributes(Attributes6 attributes) {
            this.attributes = attributes;
            return this;
        }

        /**
         * Setter for relationships.
         * @param  relationships  Relationships3 value for relationships.
         * @return Builder
         */
        public Builder relationships(Relationships3 relationships) {
            this.relationships = relationships;
            return this;
        }

        /**
         * Setter for included.
         * @param  included  List of Object value for included.
         * @return Builder
         */
        public Builder included(List<Object> included) {
            this.included = included;
            return this;
        }

        /**
         * Builds a new {@link Data24} object using the set fields.
         * @return {@link Data24}
         */
        public Data24 build() {
            return new Data24(type, id, attributes, relationships, included);
        }
    }
}
