/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.insurtech.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Endorsement type.
 */
public class Endorsement {
    private Data20 data;

    /**
     * Default constructor.
     */
    public Endorsement() {
    }

    /**
     * Initialization constructor.
     * @param  data  Data20 value for data.
     */
    public Endorsement(
            Data20 data) {
        this.data = data;
    }

    /**
     * Getter for Data.
     * Provided data for this endorsement relationship.
     * @return Returns the Data20
     */
    @JsonGetter("data")
    public Data20 getData() {
        return data;
    }

    /**
     * Setter for Data.
     * Provided data for this endorsement relationship.
     * @param data Value for Data20
     */
    @JsonSetter("data")
    public void setData(Data20 data) {
        this.data = data;
    }

    /**
     * Converts this Endorsement into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Endorsement [" + "data=" + data + "]";
    }

    /**
     * Builds a new {@link Endorsement.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Endorsement.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(data);
        return builder;
    }

    /**
     * Class to build instances of {@link Endorsement}.
     */
    public static class Builder {
        private Data20 data;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  data  Data20 value for data.
         */
        public Builder(Data20 data) {
            this.data = data;
        }

        /**
         * Setter for data.
         * @param  data  Data20 value for data.
         * @return Builder
         */
        public Builder data(Data20 data) {
            this.data = data;
            return this;
        }

        /**
         * Builds a new {@link Endorsement} object using the set fields.
         * @return {@link Endorsement}
         */
        public Endorsement build() {
            return new Endorsement(data);
        }
    }
}
