/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.insurtech.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Errors1 type.
 */
public class Errors1 {
    private String title;
    private String detail;

    /**
     * Default constructor.
     */
    public Errors1() {
    }

    /**
     * Initialization constructor.
     * @param  title  String value for title.
     * @param  detail  String value for detail.
     */
    public Errors1(
            String title,
            String detail) {
        this.title = title;
        this.detail = detail;
    }

    /**
     * Getter for Title.
     * Type of error.
     * @return Returns the String
     */
    @JsonGetter("title")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getTitle() {
        return title;
    }

    /**
     * Setter for Title.
     * Type of error.
     * @param title Value for String
     */
    @JsonSetter("title")
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Getter for Detail.
     * Detailed information about the error.
     * @return Returns the String
     */
    @JsonGetter("detail")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getDetail() {
        return detail;
    }

    /**
     * Setter for Detail.
     * Detailed information about the error.
     * @param detail Value for String
     */
    @JsonSetter("detail")
    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * Converts this Errors1 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Errors1 [" + "title=" + title + ", detail=" + detail + "]";
    }

    /**
     * Builds a new {@link Errors1.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Errors1.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .title(getTitle())
                .detail(getDetail());
        return builder;
    }

    /**
     * Class to build instances of {@link Errors1}.
     */
    public static class Builder {
        private String title;
        private String detail;



        /**
         * Setter for title.
         * @param  title  String value for title.
         * @return Builder
         */
        public Builder title(String title) {
            this.title = title;
            return this;
        }

        /**
         * Setter for detail.
         * @param  detail  String value for detail.
         * @return Builder
         */
        public Builder detail(String detail) {
            this.detail = detail;
            return this;
        }

        /**
         * Builds a new {@link Errors1} object using the set fields.
         * @return {@link Errors1}
         */
        public Errors1 build() {
            return new Errors1(title, detail);
        }
    }
}
