/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.insurtech.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Errors type.
 */
public class Errors {
    private String error;
    private String errorDescription;

    /**
     * Default constructor.
     */
    public Errors() {
    }

    /**
     * Initialization constructor.
     * @param  error  String value for error.
     * @param  errorDescription  String value for errorDescription.
     */
    public Errors(
            String error,
            String errorDescription) {
        this.error = error;
        this.errorDescription = errorDescription;
    }

    /**
     * Getter for Error.
     * Type of error.
     * @return Returns the String
     */
    @JsonGetter("error")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getError() {
        return error;
    }

    /**
     * Setter for Error.
     * Type of error.
     * @param error Value for String
     */
    @JsonSetter("error")
    public void setError(String error) {
        this.error = error;
    }

    /**
     * Getter for ErrorDescription.
     * Detailed information about the error.
     * @return Returns the String
     */
    @JsonGetter("error_description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getErrorDescription() {
        return errorDescription;
    }

    /**
     * Setter for ErrorDescription.
     * Detailed information about the error.
     * @param errorDescription Value for String
     */
    @JsonSetter("error_description")
    public void setErrorDescription(String errorDescription) {
        this.errorDescription = errorDescription;
    }

    /**
     * Converts this Errors into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Errors [" + "error=" + error + ", errorDescription=" + errorDescription + "]";
    }

    /**
     * Builds a new {@link Errors.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Errors.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .error(getError())
                .errorDescription(getErrorDescription());
        return builder;
    }

    /**
     * Class to build instances of {@link Errors}.
     */
    public static class Builder {
        private String error;
        private String errorDescription;



        /**
         * Setter for error.
         * @param  error  String value for error.
         * @return Builder
         */
        public Builder error(String error) {
            this.error = error;
            return this;
        }

        /**
         * Setter for errorDescription.
         * @param  errorDescription  String value for errorDescription.
         * @return Builder
         */
        public Builder errorDescription(String errorDescription) {
            this.errorDescription = errorDescription;
            return this;
        }

        /**
         * Builds a new {@link Errors} object using the set fields.
         * @return {@link Errors}
         */
        public Errors build() {
            return new Errors(error, errorDescription);
        }
    }
}
