/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.insurtech.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Included31 type.
 */
public class Included31 {
    private String type;
    private String lid;
    private Attributes11 attributes;

    /**
     * Default constructor.
     */
    public Included31() {
        type = "customer";
    }

    /**
     * Initialization constructor.
     * @param  type  String value for type.
     * @param  lid  String value for lid.
     * @param  attributes  Attributes11 value for attributes.
     */
    public Included31(
            String type,
            String lid,
            Attributes11 attributes) {
        this.type = type;
        this.lid = lid;
        this.attributes = attributes;
    }

    /**
     * Getter for Type.
     * The type of resource being represented.
     * @return Returns the String
     */
    @JsonGetter("type")
    public String getType() {
        return type;
    }

    /**
     * Setter for Type.
     * The type of resource being represented.
     * @param type Value for String
     */
    @JsonSetter("type")
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Getter for Lid.
     * The local ID that ties this resource to a related object in `data.relationships`.
     * @return Returns the String
     */
    @JsonGetter("lid")
    public String getLid() {
        return lid;
    }

    /**
     * Setter for Lid.
     * The local ID that ties this resource to a related object in `data.relationships`.
     * @param lid Value for String
     */
    @JsonSetter("lid")
    public void setLid(String lid) {
        this.lid = lid;
    }

    /**
     * Getter for Attributes.
     * The insured entity.
     * @return Returns the Attributes11
     */
    @JsonGetter("attributes")
    public Attributes11 getAttributes() {
        return attributes;
    }

    /**
     * Setter for Attributes.
     * The insured entity.
     * @param attributes Value for Attributes11
     */
    @JsonSetter("attributes")
    public void setAttributes(Attributes11 attributes) {
        this.attributes = attributes;
    }

    /**
     * Converts this Included31 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Included31 [" + "type=" + type + ", lid=" + lid + ", attributes=" + attributes
                + "]";
    }

    /**
     * Builds a new {@link Included31.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Included31.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(type, lid, attributes);
        return builder;
    }

    /**
     * Class to build instances of {@link Included31}.
     */
    public static class Builder {
        private String type = "customer";
        private String lid;
        private Attributes11 attributes;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  type  String value for type.
         * @param  lid  String value for lid.
         * @param  attributes  Attributes11 value for attributes.
         */
        public Builder(String type, String lid, Attributes11 attributes) {
            this.type = type;
            this.lid = lid;
            this.attributes = attributes;
        }

        /**
         * Setter for type.
         * @param  type  String value for type.
         * @return Builder
         */
        public Builder type(String type) {
            this.type = type;
            return this;
        }

        /**
         * Setter for lid.
         * @param  lid  String value for lid.
         * @return Builder
         */
        public Builder lid(String lid) {
            this.lid = lid;
            return this;
        }

        /**
         * Setter for attributes.
         * @param  attributes  Attributes11 value for attributes.
         * @return Builder
         */
        public Builder attributes(Attributes11 attributes) {
            this.attributes = attributes;
            return this;
        }

        /**
         * Builds a new {@link Included31} object using the set fields.
         * @return {@link Included31}
         */
        public Included31 build() {
            return new Included31(type, lid, attributes);
        }
    }
}
