/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.insurtech.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.UUID;

/**
 * This is a model class for Included41 type.
 */
public class Included41 {
    private String type;
    private UUID id;
    private String lid;
    private Attributes11 attributes;
    private Relationships13 relationships;

    /**
     * Default constructor.
     */
    public Included41() {
        type = "customer";
    }

    /**
     * Initialization constructor.
     * @param  type  String value for type.
     * @param  id  UUID value for id.
     * @param  lid  String value for lid.
     * @param  attributes  Attributes11 value for attributes.
     * @param  relationships  Relationships13 value for relationships.
     */
    public Included41(
            String type,
            UUID id,
            String lid,
            Attributes11 attributes,
            Relationships13 relationships) {
        this.type = type;
        this.id = id;
        this.lid = lid;
        this.attributes = attributes;
        this.relationships = relationships;
    }

    /**
     * Getter for Type.
     * The type of resource being represented.
     * @return Returns the String
     */
    @JsonGetter("type")
    public String getType() {
        return type;
    }

    /**
     * Setter for Type.
     * The type of resource being represented.
     * @param type Value for String
     */
    @JsonSetter("type")
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Getter for Id.
     * Unique Boost-generated UUID that identifies this resource.
     * @return Returns the UUID
     */
    @JsonGetter("id")
    public UUID getId() {
        return id;
    }

    /**
     * Setter for Id.
     * Unique Boost-generated UUID that identifies this resource.
     * @param id Value for UUID
     */
    @JsonSetter("id")
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for Lid.
     * The local ID that ties this resource to a related object in `data.relationships`.
     * @return Returns the String
     */
    @JsonGetter("lid")
    public String getLid() {
        return lid;
    }

    /**
     * Setter for Lid.
     * The local ID that ties this resource to a related object in `data.relationships`.
     * @param lid Value for String
     */
    @JsonSetter("lid")
    public void setLid(String lid) {
        this.lid = lid;
    }

    /**
     * Getter for Attributes.
     * The insured entity.
     * @return Returns the Attributes11
     */
    @JsonGetter("attributes")
    public Attributes11 getAttributes() {
        return attributes;
    }

    /**
     * Setter for Attributes.
     * The insured entity.
     * @param attributes Value for Attributes11
     */
    @JsonSetter("attributes")
    public void setAttributes(Attributes11 attributes) {
        this.attributes = attributes;
    }

    /**
     * Getter for Relationships.
     * Related items.
     * @return Returns the Relationships13
     */
    @JsonGetter("relationships")
    public Relationships13 getRelationships() {
        return relationships;
    }

    /**
     * Setter for Relationships.
     * Related items.
     * @param relationships Value for Relationships13
     */
    @JsonSetter("relationships")
    public void setRelationships(Relationships13 relationships) {
        this.relationships = relationships;
    }

    /**
     * Converts this Included41 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Included41 [" + "type=" + type + ", id=" + id + ", lid=" + lid + ", attributes="
                + attributes + ", relationships=" + relationships + "]";
    }

    /**
     * Builds a new {@link Included41.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Included41.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(type, id, lid, attributes, relationships);
        return builder;
    }

    /**
     * Class to build instances of {@link Included41}.
     */
    public static class Builder {
        private String type = "customer";
        private UUID id;
        private String lid;
        private Attributes11 attributes;
        private Relationships13 relationships;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  type  String value for type.
         * @param  id  UUID value for id.
         * @param  lid  String value for lid.
         * @param  attributes  Attributes11 value for attributes.
         * @param  relationships  Relationships13 value for relationships.
         */
        public Builder(String type, UUID id, String lid, Attributes11 attributes,
                Relationships13 relationships) {
            this.type = type;
            this.id = id;
            this.lid = lid;
            this.attributes = attributes;
            this.relationships = relationships;
        }

        /**
         * Setter for type.
         * @param  type  String value for type.
         * @return Builder
         */
        public Builder type(String type) {
            this.type = type;
            return this;
        }

        /**
         * Setter for id.
         * @param  id  UUID value for id.
         * @return Builder
         */
        public Builder id(UUID id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for lid.
         * @param  lid  String value for lid.
         * @return Builder
         */
        public Builder lid(String lid) {
            this.lid = lid;
            return this;
        }

        /**
         * Setter for attributes.
         * @param  attributes  Attributes11 value for attributes.
         * @return Builder
         */
        public Builder attributes(Attributes11 attributes) {
            this.attributes = attributes;
            return this;
        }

        /**
         * Setter for relationships.
         * @param  relationships  Relationships13 value for relationships.
         * @return Builder
         */
        public Builder relationships(Relationships13 relationships) {
            this.relationships = relationships;
            return this;
        }

        /**
         * Builds a new {@link Included41} object using the set fields.
         * @return {@link Included41}
         */
        public Included41 build() {
            return new Included41(type, id, lid, attributes, relationships);
        }
    }
}
