/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.insurtech.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for InstallmentPlan type.
 */
public class InstallmentPlan {
    private Data18 data;

    /**
     * Default constructor.
     */
    public InstallmentPlan() {
    }

    /**
     * Initialization constructor.
     * @param  data  Data18 value for data.
     */
    public InstallmentPlan(
            Data18 data) {
        this.data = data;
    }

    /**
     * Getter for Data.
     * Provided data for this installment plan relationship.
     * @return Returns the Data18
     */
    @JsonGetter("data")
    public Data18 getData() {
        return data;
    }

    /**
     * Setter for Data.
     * Provided data for this installment plan relationship.
     * @param data Value for Data18
     */
    @JsonSetter("data")
    public void setData(Data18 data) {
        this.data = data;
    }

    /**
     * Converts this InstallmentPlan into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "InstallmentPlan [" + "data=" + data + "]";
    }

    /**
     * Builds a new {@link InstallmentPlan.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link InstallmentPlan.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(data);
        return builder;
    }

    /**
     * Class to build instances of {@link InstallmentPlan}.
     */
    public static class Builder {
        private Data18 data;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  data  Data18 value for data.
         */
        public Builder(Data18 data) {
            this.data = data;
        }

        /**
         * Setter for data.
         * @param  data  Data18 value for data.
         * @return Builder
         */
        public Builder data(Data18 data) {
            this.data = data;
            return this;
        }

        /**
         * Builds a new {@link InstallmentPlan} object using the set fields.
         * @return {@link InstallmentPlan}
         */
        public InstallmentPlan build() {
            return new InstallmentPlan(data);
        }
    }
}
