/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.insurtech.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import dev.insurtech.api.DateTimeHelper;
import java.time.LocalDate;

/**
 * This is a model class for InstallmentPlan2 type.
 */
public class InstallmentPlan2 {
    private LocalDate billingPeriod;
    private String amountDue;
    private LocalDate dueDate;
    private String taxes;
    private String fees;

    /**
     * Default constructor.
     */
    public InstallmentPlan2() {
    }

    /**
     * Initialization constructor.
     * @param  billingPeriod  LocalDate value for billingPeriod.
     * @param  amountDue  String value for amountDue.
     * @param  dueDate  LocalDate value for dueDate.
     * @param  taxes  String value for taxes.
     * @param  fees  String value for fees.
     */
    public InstallmentPlan2(
            LocalDate billingPeriod,
            String amountDue,
            LocalDate dueDate,
            String taxes,
            String fees) {
        this.billingPeriod = billingPeriod;
        this.amountDue = amountDue;
        this.dueDate = dueDate;
        this.taxes = taxes;
        this.fees = fees;
    }

    /**
     * Getter for BillingPeriod.
     * The billing period for this installment plan entry.
     * @return Returns the LocalDate
     */
    @JsonGetter("billing_period")
    @JsonSerialize(using = DateTimeHelper.SimpleDateSerializer.class)
    public LocalDate getBillingPeriod() {
        return billingPeriod;
    }

    /**
     * Setter for BillingPeriod.
     * The billing period for this installment plan entry.
     * @param billingPeriod Value for LocalDate
     */
    @JsonSetter("billing_period")
    @JsonDeserialize(using = DateTimeHelper.SimpleDateDeserializer.class)
    public void setBillingPeriod(LocalDate billingPeriod) {
        this.billingPeriod = billingPeriod;
    }

    /**
     * Getter for AmountDue.
     * Boost generated amount due for this installment plan entry.
     * @return Returns the String
     */
    @JsonGetter("amount_due")
    public String getAmountDue() {
        return amountDue;
    }

    /**
     * Setter for AmountDue.
     * Boost generated amount due for this installment plan entry.
     * @param amountDue Value for String
     */
    @JsonSetter("amount_due")
    public void setAmountDue(String amountDue) {
        this.amountDue = amountDue;
    }

    /**
     * Getter for DueDate.
     * The date on which payment is due for this billing period.
     * @return Returns the LocalDate
     */
    @JsonGetter("due_date")
    @JsonSerialize(using = DateTimeHelper.SimpleDateSerializer.class)
    public LocalDate getDueDate() {
        return dueDate;
    }

    /**
     * Setter for DueDate.
     * The date on which payment is due for this billing period.
     * @param dueDate Value for LocalDate
     */
    @JsonSetter("due_date")
    @JsonDeserialize(using = DateTimeHelper.SimpleDateDeserializer.class)
    public void setDueDate(LocalDate dueDate) {
        this.dueDate = dueDate;
    }

    /**
     * Getter for Taxes.
     * Boost generated taxes due for this installment plan entry.
     * @return Returns the String
     */
    @JsonGetter("taxes")
    public String getTaxes() {
        return taxes;
    }

    /**
     * Setter for Taxes.
     * Boost generated taxes due for this installment plan entry.
     * @param taxes Value for String
     */
    @JsonSetter("taxes")
    public void setTaxes(String taxes) {
        this.taxes = taxes;
    }

    /**
     * Getter for Fees.
     * Boost generated fees due for this installment plan entry.
     * @return Returns the String
     */
    @JsonGetter("fees")
    public String getFees() {
        return fees;
    }

    /**
     * Setter for Fees.
     * Boost generated fees due for this installment plan entry.
     * @param fees Value for String
     */
    @JsonSetter("fees")
    public void setFees(String fees) {
        this.fees = fees;
    }

    /**
     * Converts this InstallmentPlan2 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "InstallmentPlan2 [" + "billingPeriod=" + billingPeriod + ", amountDue=" + amountDue
                + ", dueDate=" + dueDate + ", taxes=" + taxes + ", fees=" + fees + "]";
    }

    /**
     * Builds a new {@link InstallmentPlan2.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link InstallmentPlan2.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(billingPeriod, amountDue, dueDate, taxes, fees);
        return builder;
    }

    /**
     * Class to build instances of {@link InstallmentPlan2}.
     */
    public static class Builder {
        private LocalDate billingPeriod;
        private String amountDue;
        private LocalDate dueDate;
        private String taxes;
        private String fees;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  billingPeriod  LocalDate value for billingPeriod.
         * @param  amountDue  String value for amountDue.
         * @param  dueDate  LocalDate value for dueDate.
         * @param  taxes  String value for taxes.
         * @param  fees  String value for fees.
         */
        public Builder(LocalDate billingPeriod, String amountDue, LocalDate dueDate, String taxes,
                String fees) {
            this.billingPeriod = billingPeriod;
            this.amountDue = amountDue;
            this.dueDate = dueDate;
            this.taxes = taxes;
            this.fees = fees;
        }

        /**
         * Setter for billingPeriod.
         * @param  billingPeriod  LocalDate value for billingPeriod.
         * @return Builder
         */
        public Builder billingPeriod(LocalDate billingPeriod) {
            this.billingPeriod = billingPeriod;
            return this;
        }

        /**
         * Setter for amountDue.
         * @param  amountDue  String value for amountDue.
         * @return Builder
         */
        public Builder amountDue(String amountDue) {
            this.amountDue = amountDue;
            return this;
        }

        /**
         * Setter for dueDate.
         * @param  dueDate  LocalDate value for dueDate.
         * @return Builder
         */
        public Builder dueDate(LocalDate dueDate) {
            this.dueDate = dueDate;
            return this;
        }

        /**
         * Setter for taxes.
         * @param  taxes  String value for taxes.
         * @return Builder
         */
        public Builder taxes(String taxes) {
            this.taxes = taxes;
            return this;
        }

        /**
         * Setter for fees.
         * @param  fees  String value for fees.
         * @return Builder
         */
        public Builder fees(String fees) {
            this.fees = fees;
            return this;
        }

        /**
         * Builds a new {@link InstallmentPlan2} object using the set fields.
         * @return {@link InstallmentPlan2}
         */
        public InstallmentPlan2 build() {
            return new InstallmentPlan2(billingPeriod, amountDue, dueDate, taxes, fees);
        }
    }
}
