/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.insurtech.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for InsuredRisk2 type.
 */
public class InsuredRisk2 {
    private Data42 data;

    /**
     * Default constructor.
     */
    public InsuredRisk2() {
    }

    /**
     * Initialization constructor.
     * @param  data  Data42 value for data.
     */
    public InsuredRisk2(
            Data42 data) {
        this.data = data;
    }

    /**
     * Getter for Data.
     * Provided data for this insured risk relationship with local ID.
     * @return Returns the Data42
     */
    @JsonGetter("data")
    public Data42 getData() {
        return data;
    }

    /**
     * Setter for Data.
     * Provided data for this insured risk relationship with local ID.
     * @param data Value for Data42
     */
    @JsonSetter("data")
    public void setData(Data42 data) {
        this.data = data;
    }

    /**
     * Converts this InsuredRisk2 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "InsuredRisk2 [" + "data=" + data + "]";
    }

    /**
     * Builds a new {@link InsuredRisk2.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link InsuredRisk2.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(data);
        return builder;
    }

    /**
     * Class to build instances of {@link InsuredRisk2}.
     */
    public static class Builder {
        private Data42 data;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  data  Data42 value for data.
         */
        public Builder(Data42 data) {
            this.data = data;
        }

        /**
         * Setter for data.
         * @param  data  Data42 value for data.
         * @return Builder
         */
        public Builder data(Data42 data) {
            this.data = data;
            return this;
        }

        /**
         * Builds a new {@link InsuredRisk2} object using the set fields.
         * @return {@link InsuredRisk2}
         */
        public InsuredRisk2 build() {
            return new InsuredRisk2(data);
        }
    }
}
