/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.insurtech.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for InsuredRisksResponse type.
 */
public class InsuredRisksResponse {
    private Data3 data;

    /**
     * Default constructor.
     */
    public InsuredRisksResponse() {
    }

    /**
     * Initialization constructor.
     * @param  data  Data3 value for data.
     */
    public InsuredRisksResponse(
            Data3 data) {
        this.data = data;
    }

    /**
     * Getter for Data.
     * @return Returns the Data3
     */
    @JsonGetter("data")
    public Data3 getData() {
        return data;
    }

    /**
     * Setter for Data.
     * @param data Value for Data3
     */
    @JsonSetter("data")
    public void setData(Data3 data) {
        this.data = data;
    }

    /**
     * Converts this InsuredRisksResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "InsuredRisksResponse [" + "data=" + data + "]";
    }

    /**
     * Builds a new {@link InsuredRisksResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link InsuredRisksResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(data);
        return builder;
    }

    /**
     * Class to build instances of {@link InsuredRisksResponse}.
     */
    public static class Builder {
        private Data3 data;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  data  Data3 value for data.
         */
        public Builder(Data3 data) {
            this.data = data;
        }

        /**
         * Setter for data.
         * @param  data  Data3 value for data.
         * @return Builder
         */
        public Builder data(Data3 data) {
            this.data = data;
            return this;
        }

        /**
         * Builds a new {@link InsuredRisksResponse} object using the set fields.
         * @return {@link InsuredRisksResponse}
         */
        public InsuredRisksResponse build() {
            return new InsuredRisksResponse(data);
        }
    }
}
