/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.insurtech.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for InsuredRisksRequest type.
 */
public class InsuredRisksRequest {
    private Data data;

    /**
     * Default constructor.
     */
    public InsuredRisksRequest() {
    }

    /**
     * Initialization constructor.
     * @param  data  Data value for data.
     */
    public InsuredRisksRequest(
            Data data) {
        this.data = data;
    }

    /**
     * Getter for Data.
     * All values that describe this Insured Risk resource.
     * @return Returns the Data
     */
    @JsonGetter("data")
    public Data getData() {
        return data;
    }

    /**
     * Setter for Data.
     * All values that describe this Insured Risk resource.
     * @param data Value for Data
     */
    @JsonSetter("data")
    public void setData(Data data) {
        this.data = data;
    }

    /**
     * Converts this InsuredRisksRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "InsuredRisksRequest [" + "data=" + data + "]";
    }

    /**
     * Builds a new {@link InsuredRisksRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link InsuredRisksRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(data);
        return builder;
    }

    /**
     * Class to build instances of {@link InsuredRisksRequest}.
     */
    public static class Builder {
        private Data data;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  data  Data value for data.
         */
        public Builder(Data data) {
            this.data = data;
        }

        /**
         * Setter for data.
         * @param  data  Data value for data.
         * @return Builder
         */
        public Builder data(Data data) {
            this.data = data;
            return this;
        }

        /**
         * Builds a new {@link InsuredRisksRequest} object using the set fields.
         * @return {@link InsuredRisksRequest}
         */
        public InsuredRisksRequest build() {
            return new InsuredRisksRequest(data);
        }
    }
}
