/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.insurtech.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for InsuredRisk3 type.
 */
public class InsuredRisk3 {
    private Data47 data;

    /**
     * Default constructor.
     */
    public InsuredRisk3() {
    }

    /**
     * Initialization constructor.
     * @param  data  Data47 value for data.
     */
    public InsuredRisk3(
            Data47 data) {
        this.data = data;
    }

    /**
     * Getter for Data.
     * Provided data for this customer relationship.
     * @return Returns the Data47
     */
    @JsonGetter("data")
    public Data47 getData() {
        return data;
    }

    /**
     * Setter for Data.
     * Provided data for this customer relationship.
     * @param data Value for Data47
     */
    @JsonSetter("data")
    public void setData(Data47 data) {
        this.data = data;
    }

    /**
     * Converts this InsuredRisk3 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "InsuredRisk3 [" + "data=" + data + "]";
    }

    /**
     * Builds a new {@link InsuredRisk3.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link InsuredRisk3.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(data);
        return builder;
    }

    /**
     * Class to build instances of {@link InsuredRisk3}.
     */
    public static class Builder {
        private Data47 data;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  data  Data47 value for data.
         */
        public Builder(Data47 data) {
            this.data = data;
        }

        /**
         * Setter for data.
         * @param  data  Data47 value for data.
         * @return Builder
         */
        public Builder data(Data47 data) {
            this.data = data;
            return this;
        }

        /**
         * Builds a new {@link InsuredRisk3} object using the set fields.
         * @return {@link InsuredRisk3}
         */
        public InsuredRisk3 build() {
            return new InsuredRisk3(data);
        }
    }
}
