/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.insurtech.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for InsuredRisk type.
 */
public class InsuredRisk {
    private Data11 data;

    /**
     * Default constructor.
     */
    public InsuredRisk() {
    }

    /**
     * Initialization constructor.
     * @param  data  Data11 value for data.
     */
    public InsuredRisk(
            Data11 data) {
        this.data = data;
    }

    /**
     * Getter for Data.
     * Provided data for this insured risk relationship.
     * @return Returns the Data11
     */
    @JsonGetter("data")
    public Data11 getData() {
        return data;
    }

    /**
     * Setter for Data.
     * Provided data for this insured risk relationship.
     * @param data Value for Data11
     */
    @JsonSetter("data")
    public void setData(Data11 data) {
        this.data = data;
    }

    /**
     * Converts this InsuredRisk into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "InsuredRisk [" + "data=" + data + "]";
    }

    /**
     * Builds a new {@link InsuredRisk.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link InsuredRisk.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(data);
        return builder;
    }

    /**
     * Class to build instances of {@link InsuredRisk}.
     */
    public static class Builder {
        private Data11 data;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  data  Data11 value for data.
         */
        public Builder(Data11 data) {
            this.data = data;
        }

        /**
         * Setter for data.
         * @param  data  Data11 value for data.
         * @return Builder
         */
        public Builder data(Data11 data) {
            this.data = data;
            return this;
        }

        /**
         * Builds a new {@link InsuredRisk} object using the set fields.
         * @return {@link InsuredRisk}
         */
        public InsuredRisk build() {
            return new InsuredRisk(data);
        }
    }
}
