/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.insurtech.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for MailingAddress type.
 */
public class MailingAddress {
    private String address1;
    private String address2;
    private String city;
    private StateEnum state;
    private String zip;

    /**
     * Default constructor.
     */
    public MailingAddress() {
    }

    /**
     * Initialization constructor.
     * @param  address1  String value for address1.
     * @param  city  String value for city.
     * @param  state  StateEnum value for state.
     * @param  zip  String value for zip.
     * @param  address2  String value for address2.
     */
    public MailingAddress(
            String address1,
            String city,
            StateEnum state,
            String zip,
            String address2) {
        this.address1 = address1;
        this.address2 = address2;
        this.city = city;
        this.state = state;
        this.zip = zip;
    }

    /**
     * Getter for Address1.
     * The first line of the address.
     * @return Returns the String
     */
    @JsonGetter("address1")
    public String getAddress1() {
        return address1;
    }

    /**
     * Setter for Address1.
     * The first line of the address.
     * @param address1 Value for String
     */
    @JsonSetter("address1")
    public void setAddress1(String address1) {
        this.address1 = address1;
    }

    /**
     * Getter for Address2.
     * The second line of the address.
     * @return Returns the String
     */
    @JsonGetter("address2")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAddress2() {
        return address2;
    }

    /**
     * Setter for Address2.
     * The second line of the address.
     * @param address2 Value for String
     */
    @JsonSetter("address2")
    public void setAddress2(String address2) {
        this.address2 = address2;
    }

    /**
     * Getter for City.
     * The city of the address.
     * @return Returns the String
     */
    @JsonGetter("city")
    public String getCity() {
        return city;
    }

    /**
     * Setter for City.
     * The city of the address.
     * @param city Value for String
     */
    @JsonSetter("city")
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * Getter for State.
     * Two letter state code of the address.
     * @return Returns the StateEnum
     */
    @JsonGetter("state")
    public StateEnum getState() {
        return state;
    }

    /**
     * Setter for State.
     * Two letter state code of the address.
     * @param state Value for StateEnum
     */
    @JsonSetter("state")
    public void setState(StateEnum state) {
        this.state = state;
    }

    /**
     * Getter for Zip.
     * 5 or 10 character postal code of the address.
     * @return Returns the String
     */
    @JsonGetter("zip")
    public String getZip() {
        return zip;
    }

    /**
     * Setter for Zip.
     * 5 or 10 character postal code of the address.
     * @param zip Value for String
     */
    @JsonSetter("zip")
    public void setZip(String zip) {
        this.zip = zip;
    }

    /**
     * Converts this MailingAddress into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "MailingAddress [" + "address1=" + address1 + ", city=" + city + ", state=" + state
                + ", zip=" + zip + ", address2=" + address2 + "]";
    }

    /**
     * Builds a new {@link MailingAddress.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link MailingAddress.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(address1, city, state, zip)
                .address2(getAddress2());
        return builder;
    }

    /**
     * Class to build instances of {@link MailingAddress}.
     */
    public static class Builder {
        private String address1;
        private String city;
        private StateEnum state;
        private String zip;
        private String address2;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  address1  String value for address1.
         * @param  city  String value for city.
         * @param  state  StateEnum value for state.
         * @param  zip  String value for zip.
         */
        public Builder(String address1, String city, StateEnum state, String zip) {
            this.address1 = address1;
            this.city = city;
            this.state = state;
            this.zip = zip;
        }

        /**
         * Setter for address1.
         * @param  address1  String value for address1.
         * @return Builder
         */
        public Builder address1(String address1) {
            this.address1 = address1;
            return this;
        }

        /**
         * Setter for city.
         * @param  city  String value for city.
         * @return Builder
         */
        public Builder city(String city) {
            this.city = city;
            return this;
        }

        /**
         * Setter for state.
         * @param  state  StateEnum value for state.
         * @return Builder
         */
        public Builder state(StateEnum state) {
            this.state = state;
            return this;
        }

        /**
         * Setter for zip.
         * @param  zip  String value for zip.
         * @return Builder
         */
        public Builder zip(String zip) {
            this.zip = zip;
            return this;
        }

        /**
         * Setter for address2.
         * @param  address2  String value for address2.
         * @return Builder
         */
        public Builder address2(String address2) {
            this.address2 = address2;
            return this;
        }

        /**
         * Builds a new {@link MailingAddress} object using the set fields.
         * @return {@link MailingAddress}
         */
        public MailingAddress build() {
            return new MailingAddress(address1, city, state, zip, address2);
        }
    }
}
