/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.insurtech.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Meta type.
 */
public class Meta {
    private Integer count;

    /**
     * Default constructor.
     */
    public Meta() {
    }

    /**
     * Initialization constructor.
     * @param  count  Integer value for count.
     */
    public Meta(
            Integer count) {
        this.count = count;
    }

    /**
     * Getter for Count.
     * The number of related objects of this type.
     * @return Returns the Integer
     */
    @JsonGetter("count")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getCount() {
        return count;
    }

    /**
     * Setter for Count.
     * The number of related objects of this type.
     * @param count Value for Integer
     */
    @JsonSetter("count")
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * Converts this Meta into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Meta [" + "count=" + count + "]";
    }

    /**
     * Builds a new {@link Meta.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Meta.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .count(getCount());
        return builder;
    }

    /**
     * Class to build instances of {@link Meta}.
     */
    public static class Builder {
        private Integer count;



        /**
         * Setter for count.
         * @param  count  Integer value for count.
         * @return Builder
         */
        public Builder count(Integer count) {
            this.count = count;
            return this;
        }

        /**
         * Builds a new {@link Meta} object using the set fields.
         * @return {@link Meta}
         */
        public Meta build() {
            return new Meta(count);
        }
    }
}
