/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.insurtech.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for PoliciesResponse type.
 */
public class PoliciesResponse {
    private Data9 data;
    private List<Object> included;

    /**
     * Default constructor.
     */
    public PoliciesResponse() {
    }

    /**
     * Initialization constructor.
     * @param  data  Data9 value for data.
     * @param  included  List of Object value for included.
     */
    public PoliciesResponse(
            Data9 data,
            List<Object> included) {
        this.data = data;
        this.included = included;
    }

    /**
     * Getter for Data.
     * @return Returns the Data9
     */
    @JsonGetter("data")
    public Data9 getData() {
        return data;
    }

    /**
     * Setter for Data.
     * @param data Value for Data9
     */
    @JsonSetter("data")
    public void setData(Data9 data) {
        this.data = data;
    }

    /**
     * Getter for Included.
     * Array of included objects which provide additional data about an object from the above
     * `data.relationships`.
     * @return Returns the List of Object
     */
    @JsonGetter("included")
    public List<Object> getIncluded() {
        return included;
    }

    /**
     * Setter for Included.
     * Array of included objects which provide additional data about an object from the above
     * `data.relationships`.
     * @param included Value for List of Object
     */
    @JsonSetter("included")
    public void setIncluded(List<Object> included) {
        this.included = included;
    }

    /**
     * Converts this PoliciesResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PoliciesResponse [" + "data=" + data + ", included=" + included + "]";
    }

    /**
     * Builds a new {@link PoliciesResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PoliciesResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(data, included);
        return builder;
    }

    /**
     * Class to build instances of {@link PoliciesResponse}.
     */
    public static class Builder {
        private Data9 data;
        private List<Object> included;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  data  Data9 value for data.
         * @param  included  List of Object value for included.
         */
        public Builder(Data9 data, List<Object> included) {
            this.data = data;
            this.included = included;
        }

        /**
         * Setter for data.
         * @param  data  Data9 value for data.
         * @return Builder
         */
        public Builder data(Data9 data) {
            this.data = data;
            return this;
        }

        /**
         * Setter for included.
         * @param  included  List of Object value for included.
         * @return Builder
         */
        public Builder included(List<Object> included) {
            this.included = included;
            return this;
        }

        /**
         * Builds a new {@link PoliciesResponse} object using the set fields.
         * @return {@link PoliciesResponse}
         */
        public PoliciesResponse build() {
            return new PoliciesResponse(data, included);
        }
    }
}
