/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.insurtech.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Product6 type.
 */
public class Product6 {
    private Data43 data;

    /**
     * Default constructor.
     */
    public Product6() {
    }

    /**
     * Initialization constructor.
     * @param  data  Data43 value for data.
     */
    public Product6(
            Data43 data) {
        this.data = data;
    }

    /**
     * Getter for Data.
     * Provided data for this product relationship.
     * @return Returns the Data43
     */
    @JsonGetter("data")
    public Data43 getData() {
        return data;
    }

    /**
     * Setter for Data.
     * Provided data for this product relationship.
     * @param data Value for Data43
     */
    @JsonSetter("data")
    public void setData(Data43 data) {
        this.data = data;
    }

    /**
     * Converts this Product6 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Product6 [" + "data=" + data + "]";
    }

    /**
     * Builds a new {@link Product6.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Product6.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(data);
        return builder;
    }

    /**
     * Class to build instances of {@link Product6}.
     */
    public static class Builder {
        private Data43 data;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  data  Data43 value for data.
         */
        public Builder(Data43 data) {
            this.data = data;
        }

        /**
         * Setter for data.
         * @param  data  Data43 value for data.
         * @return Builder
         */
        public Builder data(Data43 data) {
            this.data = data;
            return this;
        }

        /**
         * Builds a new {@link Product6} object using the set fields.
         * @return {@link Product6}
         */
        public Product6 build() {
            return new Product6(data);
        }
    }
}
