/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.insurtech.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for QuotesRequest type.
 */
public class QuotesRequest {
    private Data39 data;
    private List<Object> included;

    /**
     * Default constructor.
     */
    public QuotesRequest() {
    }

    /**
     * Initialization constructor.
     * @param  data  Data39 value for data.
     * @param  included  List of Object value for included.
     */
    public QuotesRequest(
            Data39 data,
            List<Object> included) {
        this.data = data;
        this.included = included;
    }

    /**
     * Getter for Data.
     * All values for the request are in this top-level object.
     * @return Returns the Data39
     */
    @JsonGetter("data")
    public Data39 getData() {
        return data;
    }

    /**
     * Setter for Data.
     * All values for the request are in this top-level object.
     * @param data Value for Data39
     */
    @JsonSetter("data")
    public void setData(Data39 data) {
        this.data = data;
    }

    /**
     * Getter for Included.
     * Array of included objects.
     * @return Returns the List of Object
     */
    @JsonGetter("included")
    public List<Object> getIncluded() {
        return included;
    }

    /**
     * Setter for Included.
     * Array of included objects.
     * @param included Value for List of Object
     */
    @JsonSetter("included")
    public void setIncluded(List<Object> included) {
        this.included = included;
    }

    /**
     * Converts this QuotesRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "QuotesRequest [" + "data=" + data + ", included=" + included + "]";
    }

    /**
     * Builds a new {@link QuotesRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link QuotesRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(data, included);
        return builder;
    }

    /**
     * Class to build instances of {@link QuotesRequest}.
     */
    public static class Builder {
        private Data39 data;
        private List<Object> included;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  data  Data39 value for data.
         * @param  included  List of Object value for included.
         */
        public Builder(Data39 data, List<Object> included) {
            this.data = data;
            this.included = included;
        }

        /**
         * Setter for data.
         * @param  data  Data39 value for data.
         * @return Builder
         */
        public Builder data(Data39 data) {
            this.data = data;
            return this;
        }

        /**
         * Setter for included.
         * @param  included  List of Object value for included.
         * @return Builder
         */
        public Builder included(List<Object> included) {
            this.included = included;
            return this;
        }

        /**
         * Builds a new {@link QuotesRequest} object using the set fields.
         * @return {@link QuotesRequest}
         */
        public QuotesRequest build() {
            return new QuotesRequest(data, included);
        }
    }
}
