/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.insurtech.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Relationships4 type.
 */
public class Relationships4 {
    private Policy policy;
    private Endorsement endorsement;
    private Coverage coverage;

    /**
     * Default constructor.
     */
    public Relationships4() {
    }

    /**
     * Initialization constructor.
     * @param  policy  Policy value for policy.
     * @param  endorsement  Endorsement value for endorsement.
     * @param  coverage  Coverage value for coverage.
     */
    public Relationships4(
            Policy policy,
            Endorsement endorsement,
            Coverage coverage) {
        this.policy = policy;
        this.endorsement = endorsement;
        this.coverage = coverage;
    }

    /**
     * Getter for Policy.
     * UUID that identifies this policy.
     * @return Returns the Policy
     */
    @JsonGetter("policy")
    public Policy getPolicy() {
        return policy;
    }

    /**
     * Setter for Policy.
     * UUID that identifies this policy.
     * @param policy Value for Policy
     */
    @JsonSetter("policy")
    public void setPolicy(Policy policy) {
        this.policy = policy;
    }

    /**
     * Getter for Endorsement.
     * UUID that identifies this endorsement.
     * @return Returns the Endorsement
     */
    @JsonGetter("endorsement")
    public Endorsement getEndorsement() {
        return endorsement;
    }

    /**
     * Setter for Endorsement.
     * UUID that identifies this endorsement.
     * @param endorsement Value for Endorsement
     */
    @JsonSetter("endorsement")
    public void setEndorsement(Endorsement endorsement) {
        this.endorsement = endorsement;
    }

    /**
     * Getter for Coverage.
     * UUID that identifies this product coverage.
     * @return Returns the Coverage
     */
    @JsonGetter("coverage")
    public Coverage getCoverage() {
        return coverage;
    }

    /**
     * Setter for Coverage.
     * UUID that identifies this product coverage.
     * @param coverage Value for Coverage
     */
    @JsonSetter("coverage")
    public void setCoverage(Coverage coverage) {
        this.coverage = coverage;
    }

    /**
     * Converts this Relationships4 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Relationships4 [" + "policy=" + policy + ", endorsement=" + endorsement
                + ", coverage=" + coverage + "]";
    }

    /**
     * Builds a new {@link Relationships4.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Relationships4.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(policy, endorsement, coverage);
        return builder;
    }

    /**
     * Class to build instances of {@link Relationships4}.
     */
    public static class Builder {
        private Policy policy;
        private Endorsement endorsement;
        private Coverage coverage;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  policy  Policy value for policy.
         * @param  endorsement  Endorsement value for endorsement.
         * @param  coverage  Coverage value for coverage.
         */
        public Builder(Policy policy, Endorsement endorsement, Coverage coverage) {
            this.policy = policy;
            this.endorsement = endorsement;
            this.coverage = coverage;
        }

        /**
         * Setter for policy.
         * @param  policy  Policy value for policy.
         * @return Builder
         */
        public Builder policy(Policy policy) {
            this.policy = policy;
            return this;
        }

        /**
         * Setter for endorsement.
         * @param  endorsement  Endorsement value for endorsement.
         * @return Builder
         */
        public Builder endorsement(Endorsement endorsement) {
            this.endorsement = endorsement;
            return this;
        }

        /**
         * Setter for coverage.
         * @param  coverage  Coverage value for coverage.
         * @return Builder
         */
        public Builder coverage(Coverage coverage) {
            this.coverage = coverage;
            return this;
        }

        /**
         * Builds a new {@link Relationships4} object using the set fields.
         * @return {@link Relationships4}
         */
        public Relationships4 build() {
            return new Relationships4(policy, endorsement, coverage);
        }
    }
}
