/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.insurtech.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Relationships type.
 */
public class Relationships {
    private Agent agent;
    private Product product;

    /**
     * Default constructor.
     */
    public Relationships() {
    }

    /**
     * Initialization constructor.
     * @param  product  Product value for product.
     * @param  agent  Agent value for agent.
     */
    public Relationships(
            Product product,
            Agent agent) {
        this.agent = agent;
        this.product = product;
    }

    /**
     * Getter for Agent.
     * UUID of the agent.
     * @return Returns the Agent
     */
    @JsonGetter("agent")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Agent getAgent() {
        return agent;
    }

    /**
     * Setter for Agent.
     * UUID of the agent.
     * @param agent Value for Agent
     */
    @JsonSetter("agent")
    public void setAgent(Agent agent) {
        this.agent = agent;
    }

    /**
     * Getter for Product.
     * Boost supplied value representing the specific product type. The product's configuration
     * Determines allowable values, such as limits and deductibles.
     * @return Returns the Product
     */
    @JsonGetter("product")
    public Product getProduct() {
        return product;
    }

    /**
     * Setter for Product.
     * Boost supplied value representing the specific product type. The product's configuration
     * Determines allowable values, such as limits and deductibles.
     * @param product Value for Product
     */
    @JsonSetter("product")
    public void setProduct(Product product) {
        this.product = product;
    }

    /**
     * Converts this Relationships into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Relationships [" + "product=" + product + ", agent=" + agent + "]";
    }

    /**
     * Builds a new {@link Relationships.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Relationships.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(product)
                .agent(getAgent());
        return builder;
    }

    /**
     * Class to build instances of {@link Relationships}.
     */
    public static class Builder {
        private Product product;
        private Agent agent;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  product  Product value for product.
         */
        public Builder(Product product) {
            this.product = product;
        }

        /**
         * Setter for product.
         * @param  product  Product value for product.
         * @return Builder
         */
        public Builder product(Product product) {
            this.product = product;
            return this;
        }

        /**
         * Setter for agent.
         * @param  agent  Agent value for agent.
         * @return Builder
         */
        public Builder agent(Agent agent) {
            this.agent = agent;
            return this;
        }

        /**
         * Builds a new {@link Relationships} object using the set fields.
         * @return {@link Relationships}
         */
        public Relationships build() {
            return new Relationships(product, agent);
        }
    }
}
