/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.insurtech.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Relationships10 type.
 */
public class Relationships10 {
    private ProductCoverage productCoverage;

    /**
     * Default constructor.
     */
    public Relationships10() {
    }

    /**
     * Initialization constructor.
     * @param  productCoverage  ProductCoverage value for productCoverage.
     */
    public Relationships10(
            ProductCoverage productCoverage) {
        this.productCoverage = productCoverage;
    }

    /**
     * Getter for ProductCoverage.
     * Product coverage that applies to this policy.
     * @return Returns the ProductCoverage
     */
    @JsonGetter("product_coverage")
    public ProductCoverage getProductCoverage() {
        return productCoverage;
    }

    /**
     * Setter for ProductCoverage.
     * Product coverage that applies to this policy.
     * @param productCoverage Value for ProductCoverage
     */
    @JsonSetter("product_coverage")
    public void setProductCoverage(ProductCoverage productCoverage) {
        this.productCoverage = productCoverage;
    }

    /**
     * Converts this Relationships10 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Relationships10 [" + "productCoverage=" + productCoverage + "]";
    }

    /**
     * Builds a new {@link Relationships10.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Relationships10.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(productCoverage);
        return builder;
    }

    /**
     * Class to build instances of {@link Relationships10}.
     */
    public static class Builder {
        private ProductCoverage productCoverage;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  productCoverage  ProductCoverage value for productCoverage.
         */
        public Builder(ProductCoverage productCoverage) {
            this.productCoverage = productCoverage;
        }

        /**
         * Setter for productCoverage.
         * @param  productCoverage  ProductCoverage value for productCoverage.
         * @return Builder
         */
        public Builder productCoverage(ProductCoverage productCoverage) {
            this.productCoverage = productCoverage;
            return this;
        }

        /**
         * Builds a new {@link Relationships10} object using the set fields.
         * @return {@link Relationships10}
         */
        public Relationships10 build() {
            return new Relationships10(productCoverage);
        }
    }
}
