/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.insurtech.api.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * StatusEnum to be used.
 */
public enum StatusEnum {
    ISSUED,

    INFORCE,

    REINSTATED,

    RENEWED,

    CANCELPENDING,

    CANCELLED,

    ENUM_VOID;


    private static TreeMap<String, StatusEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        ISSUED.value = "issued";
        INFORCE.value = "in-force";
        REINSTATED.value = "reinstated";
        RENEWED.value = "renewed";
        CANCELPENDING.value = "cancel-pending";
        CANCELLED.value = "cancelled";
        ENUM_VOID.value = "void";

        valueMap.put("issued", ISSUED);
        valueMap.put("in-force", INFORCE);
        valueMap.put("reinstated", REINSTATED);
        valueMap.put("renewed", RENEWED);
        valueMap.put("cancel-pending", CANCELPENDING);
        valueMap.put("cancelled", CANCELLED);
        valueMap.put("void", ENUM_VOID);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static StatusEnum constructFromString(String toConvert) throws IOException {
        StatusEnum enumValue = fromString(toConvert);
        if (enumValue == null)
        {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static StatusEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of StatusEnum values to list of string values.
     * @param toConvert The list of StatusEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<StatusEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (StatusEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 