/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.insurtech.api.controllers;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

import dev.insurtech.api.MergedApiClient;
import dev.insurtech.api.exceptions.ApiException;
import dev.insurtech.api.models.ContentType1Enum;
import io.apimatic.core.utilities.TestHelper;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.UUID;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;

public class PolicyControllerTest extends BaseControllerTest {

    /**
     * Client instance.
     */
    private static MergedApiClient client;
    
    /**
     * Controller instance (for all tests).
     */
    private static PolicyController controller;

    /**
     * Setup test class.
     */
    @BeforeClass
    public static void setUpClass() {
        client = createConfiguration();
        controller = client.getPolicyController();
    }

    /**
     * Tear down test class.
     */
    @AfterClass
    public static void tearDownClass() {
        controller = null;
    }

    /**
     * List previously created policies .
     * @throws Throwable exception if occurs.
     */
    @Test
    public void testTestListPolicies() throws Exception {
        // Parameters for the API call
        UUID boostUser = UUID.fromString(
                "53f85c54-f471-444d-80a7-9feb1951ff46");
        ContentType1Enum accept = null;

        // Set callback and perform API call
        try {
            controller.listPolicies(boostUser, accept);
        } catch (ApiException e) {
            // Empty block
        }

        // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

        // Test headers
        Map<String, String> headers = new LinkedHashMap<String, String>();
        headers.put("Content-Type", TestHelper.NULL_STRING);
        
        assertTrue("Headers do not match", TestHelper.areHeadersProperSubsetOf(
                headers, httpResponse.getResponse().getHeaders().asSimpleMap(), true));

    }

}
