/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.insurtech.api.controllers;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

import dev.insurtech.api.MergedApiClient;
import dev.insurtech.api.exceptions.ApiException;
import dev.insurtech.api.models.OperationTypeEnum;
import io.apimatic.core.utilities.TestHelper;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;

public class SimpleCalculatorControllerTest extends BaseControllerTest {

    /**
     * Client instance.
     */
    private static MergedApiClient client;
    
    /**
     * Controller instance (for all tests).
     */
    private static SimpleCalculatorController controller;

    /**
     * Setup test class.
     */
    @BeforeClass
    public static void setUpClass() {
        client = createConfiguration();
        controller = client.getSimpleCalculatorController();
    }

    /**
     * Tear down test class.
     */
    @AfterClass
    public static void tearDownClass() {
        controller = null;
    }

    /**
     * Check if multiplication works.
     * @throws Throwable exception if occurs.
     */
    @Test
    public void testMultiply() throws Exception {
        // Parameters for the API call
        OperationTypeEnum operation = OperationTypeEnum.fromString(
                "MULTIPLY");
        double x = 4d;
        double y = 5d;

        // Set callback and perform API call
        double result = 0;
        try {
            result = controller.calculate(operation, x, y);
        } catch (ApiException e) {
            // Empty block
        }

        // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

        // Test whether the captured response is as we expected
        assertNotNull("Result does not exist", 
                result);
        assertEquals("Response does not match expected value", 
            20, result, ASSERT_PRECISION);
    }

}
